version: '3.9'

services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: fastapi-db
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
